---
# Source: job4j_k8s/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-job4j_k8s
  labels:
    helm.sh/chart: job4j_k8s-0.1.0
    app.kubernetes.io/name: job4j_k8s
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
